### Настройка подключения ansible 
ansible_user: root
ansible_ssh_private_key_file: "./ssh-key/id_rsa"
ansible_ssh_common_args: "-i {{ ansible_ssh_private_key_file }} -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o ProxyCommand='ssh -o StrictHostKeyChecking=no -i {{ ansible_ssh_private_key_file }}  -W %h:%p -q {{ ansible_user }}@{{ groups['server_fip'][0] }}'"

### Настройка генерации сертификатов
path_tls: "/etc/tls"

### Настройка node-exporter
node_exporter_version: 1.3.1
node_exporter_port: 9100
node_exporter_basic_auth_users:
 selectel: selectel

### Настройка prometheus
prometheus_version: 2.33.0
prometheus_web_listen_port: "9090"
prometheus_username_password_msg: "selectel/selectel"
prometheus_web_config:
  tls_server_config:
   cert_file: "{{ path_tls }}/node.crt"
   key_file: "{{ path_tls }}/node.key"
  http_server_config: {}
  basic_auth_users:
    selectel: $2a$12$ONubD613FhNJ9.omYDd2FOFj0/vhvihs1xjDL3ZUPcIQC99V1Nl7K #selectel/selectel

### Настройка docker
docker_edition: 'ce'
docker_version: "5:20.10.12~3-0~ubuntu-focal"
